# Yellow Taxi Trip Reports

In [1]:
import pandas as pd

In [2]:
yellow_df = pd.read_parquet("data/yellow_tripdata_2026-01.parquet")

## Exploring the data
We check for any duplicate data.

In [3]:
yellow_df[yellow_df.duplicated(subset=['tpep_pickup_datetime', 'tpep_dropoff_datetime'], keep=False)]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
74,2,2026-01-01 00:54:05,2026-01-01 00:56:36,1.0,0.63,1.0,N,143,143,4,-5.10,-1.0,-0.5,0.0,0.0,-1.0,-10.10,-2.5,0.0,0.00
75,2,2026-01-01 00:54:05,2026-01-01 00:56:36,1.0,0.63,1.0,N,143,143,4,5.10,1.0,0.5,0.0,0.0,1.0,10.10,2.5,0.0,0.00
248,2,2026-01-01 00:43:29,2026-01-01 01:09:26,1.0,1.92,1.0,N,170,79,4,-22.60,-1.0,-0.5,0.0,0.0,-1.0,-28.35,-2.5,0.0,-0.75
249,2,2026-01-01 00:43:29,2026-01-01 01:09:26,1.0,1.92,1.0,N,170,79,4,22.60,1.0,0.5,0.0,0.0,1.0,28.35,2.5,0.0,0.75
368,2,2026-01-01 00:37:39,2026-01-01 00:38:17,1.0,0.02,1.0,N,261,261,4,-3.00,-1.0,-0.5,0.0,0.0,-1.0,-8.75,-2.5,0.0,-0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3722452,1,2026-01-31 23:59:41,2026-02-01 00:11:53,NaN,1.10,NaN,NaN,107,161,0,17.85,0.0,0.5,0.0,0.0,1.0,40.66,NaN,NaN,0.75
3723020,2,2026-01-31 23:01:20,2026-01-31 23:07:31,NaN,1.06,NaN,NaN,142,237,0,11.20,0.0,0.5,0.0,0.0,1.0,15.95,NaN,NaN,0.75
3723313,1,2026-01-31 23:02:33,2026-01-31 23:10:50,NaN,1.20,NaN,NaN,125,158,0,13.87,0.0,0.5,0.0,0.0,1.0,33.87,NaN,NaN,0.75
3723586,2,2026-01-31 23:55:45,2026-02-01 00:03:55,NaN,2.34,NaN,NaN,33,148,0,29.87,0.0,0.5,0.0,0.0,1.0,34.62,NaN,NaN,0.75
3724776,2,2026-01-31 23:08:29,2026-01-31 23:24:29,NaN,2.67,NaN,NaN,7,145,0,18.28,0.0,0.5,0.0,0.0,1.0,19.78,NaN,NaN,0.00

We remove the duplicated data

In [4]:
yellow_df = yellow_df.drop_duplicates().reset_index(drop=True)
yellow_df['trip_id'] = yellow_df.index

Now we create a new dataframe with the pick up and drop off data.

In [5]:
datetimes = yellow_df[['tpep_pickup_datetime','tpep_dropoff_datetime']].reset_index(drop=True)
datetimes.head()

  tpep_pickup_datetime tpep_dropoff_datetime
0  2026-01-01 00:54:04   2026-01-01 00:59:37
1  2026-01-01 00:34:04   2026-01-01 00:39:47
2  2026-01-01 00:57:06   2026-01-01 01:05:59
3  2026-01-01 00:15:22   2026-01-01 00:58:10
4  2026-01-01 00:27:13   2026-01-01 00:40:43

### Pick up info

In [6]:
pickup_datetimes = datetimes[['tpep_pickup_datetime']].copy()
pickup_datetimes['hour'] = pickup_datetimes['tpep_pickup_datetime'].dt.hour
pickup_datetimes['day'] = pickup_datetimes['tpep_pickup_datetime'].dt.day
pickup_datetimes['month'] = pickup_datetimes['tpep_pickup_datetime'].dt.month
pickup_datetimes['year'] = pickup_datetimes['tpep_pickup_datetime'].dt.year
pickup_datetimes['weekday'] = pickup_datetimes['tpep_pickup_datetime'].dt.day_name()

In [11]:
pickup_datetimes.tail()

        tpep_pickup_datetime  hour  day  month  year   weekday
3724884  2026-01-31 23:26:00    23   31      1  2026  Saturday
3724885  2026-01-31 23:33:53    23   31      1  2026  Saturday
3724886  2026-01-31 23:40:23    23   31      1  2026  Saturday
3724887  2026-01-31 23:10:21    23   31      1  2026  Saturday
3724888  2026-01-31 23:43:12    23   31      1  2026  Saturday

### Drop off info

In [7]:
dropoff_datetimes = datetimes[['tpep_dropoff_datetime']].copy()
dropoff_datetimes['hour'] = dropoff_datetimes['tpep_dropoff_datetime'].dt.hour
dropoff_datetimes['day'] = dropoff_datetimes['tpep_dropoff_datetime'].dt.day
dropoff_datetimes['month'] = dropoff_datetimes['tpep_dropoff_datetime'].dt.month
dropoff_datetimes['year'] = dropoff_datetimes['tpep_dropoff_datetime'].dt.year
dropoff_datetimes['weekday'] = dropoff_datetimes['tpep_dropoff_datetime'].dt.day_name()

In [12]:
dropoff_datetimes.head(15)

   tpep_dropoff_datetime  hour  day  month  year   weekday
0    2026-01-01 00:59:37     0    1      1  2026  Thursday
1    2026-01-01 00:39:47     0    1      1  2026  Thursday
2    2026-01-01 01:05:59     1    1      1  2026  Thursday
3    2026-01-01 00:58:10     0    1      1  2026  Thursday
4    2026-01-01 00:40:43     0    1      1  2026  Thursday
5    2026-01-01 01:00:47     1    1      1  2026  Thursday
6    2026-01-01 00:28:32     0    1      1  2026  Thursday
7    2026-01-01 00:59:05     0    1      1  2026  Thursday
8    2026-01-01 01:11:58     1    1      1  2026  Thursday
9    2026-01-01 00:50:42     0    1      1  2026  Thursday
10   2026-01-01 00:48:58     0    1      1  2026  Thursday
11   2026-01-01 01:03:09     1    1      1  2026  Thursday
12   2026-01-01 00:49:14     0    1      1  2026  Thursday
13   2026-01-01 00:44:28     0    1      1  2026  Thursday
14   2026-01-01 00:45:12     0    1      1  2026  Thursday

In [8]:
zones = pd.read_csv("data/taxi_zone_lookup.csv")
zones.dtypes

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

In [9]:
zones

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      NaN          NaN
264         265            NaN           Outside of NYC          NaN

[265 rows x 4 columns]